version: '3.5'

services:
  db:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-shop}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - db:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
  cache:
    container_name: redis_container
    image: redis
    environment:
        ALLOW_EMPTY_PASSWORD: yes
    volumes: 
      - cache:/data
    ports:
      - '6379:6379'
    restart: unless-stopped
volumes:
    db: 
      driver: local
    cache:
      driver: local
