# Generated by Django 4.1.4 on 2023-02-01 19:49

from django.db import migrations, models
import phone_field.models
import user.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, verbose_name='Імя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Прізвище')),
                ('email', models.EmailField(max_length=70, unique=True, verbose_name='Електронна Пошта')),
                ('phone', phone_field.models.PhoneField(max_length=31, verbose_name='Номер телефону')),
                ('avatar', models.ImageField(default='default/default_avatar.png', upload_to=user.models.photo_file_name, verbose_name='Аватар')),
                ('avatar_url', models.URLField(blank=True, null=True, verbose_name='Аватар url')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Адміністратор')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('wish_list', models.ManyToManyField(to='shop.product', verbose_name='Список бажань')),
            ],
            options={
                'verbose_name': 'Користувач',
                'verbose_name_plural': 'Користувачі',
            },
        ),
    ]
