# Generated by Django 4.1.4 on 2023-01-25 20:44

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default/default_avatar.png', upload_to=user.models.photo_file_name, verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, null=True, verbose_name='Аватар url'),
        ),
    ]
