# Generated by Django 4.1.4 on 2022-12-30 14:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seria', models.CharField(max_length=100, verbose_name='Серія')),
                ('screen_diagonal', models.FloatField(verbose_name='Діагональ екрану')),
                ('screen_type', models.CharField(choices=[('IPS', 'IPS'), ('OLED', 'OLED'), ('TN', 'TN'), ('RETINA', 'Retina'), ('VA', 'VA'), ('IGZO', 'IGZO'), ('LTPS', 'LTPS'), ('Liquid_Retina', 'Liquid Retina'), ('Liquid_Retina_XDR', 'Liquid Retina XDR')], max_length=17, verbose_name='Тип екрану')),
                ('resolution', models.CharField(choices=[('P640x480', '640x480p'), ('P800x600', '800x600p'), ('P1024x768', '1024x768p'), ('P1280x720', '1280x720p (HD)'), ('P1280x768', '1280x768p'), ('P1280x1024', '1280x1024p'), ('P1366x768', '1366x768p'), ('P1400x1050', '1400x1050p'), ('P1440x900', '1440x900p'), ('P1600x1200', '1600x1200p'), ('P1680x1050', '1680x1050p'), ('P1920x1080', '1920x1080p (FullHD)'), ('P1920x1200', '1920x1200p'), ('P2560x1440', '2560x1440p (2K)'), ('P3840x2160', '3840x2160p (4K)'), ('P7580x4320', '7680x4320p (8K)'), ('P10240x4320', '10240x4320p (10K)'), ('P15360x8640', '15360x8640p (16K)')], max_length=11, verbose_name='Роздільна здатність')),
                ('integrated_videocard_aviable', models.BooleanField(verbose_name='Наявна інтегрована відеокарта')),
                ('discred_videocard_aviable', models.BooleanField(verbose_name='Наявна дискретна відеокарта')),
                ('videocard_series', models.CharField(choices=[('GEFORCE_GTX_1050', 'GeForce GTX 1050'), ('GEFORCE_GTX_1650', 'GeForce GTX 1650'), ('GEFORCE_GTX_1650_TI', 'GeForce GTX 1650 Ti'), ('GEFORCE_GTX_1660_TI', 'GeForce GTX 1660 Ti'), ('GEFORCE_GTX_2060', 'GeForce GTX 2060'), ('GEFORCE_GTX_3050', 'GeForce GTX 3050'), ('GEFORCE_GTX_3050_TI', 'GeForce GTX 3050 Ti'), ('GEFORCE_GTX_3060', 'GeForce GTX 3060'), ('GEFORCE_GTX_3070', 'GeForce GTX 3070'), ('GEFORCE_GTX_3070_TIGeForce GTX 3070 Ti', 'Geforce Gtx 3070 Ti'), ('GEFORCE_GTX_3080', 'GeForce GTX 3080'), ('GEFORCE_GTX_3080_TI', 'GeForce GTX 3080 Ti'), ('ARC_GRAPHICS', 'Arc Graphics'), ('FIRE_PRO', 'Fire Pro'), ('GEFORCE_320M', 'GeForce 320M'), ('GEFORCE_8XX_9XX_SERIES', 'GeForce 8xx/9xx Series'), ('GEFORCE_GT_730M', 'GeForce GT 730M'), ('GEFORCE_GT_750M', 'GeForce GT 750M'), ('GEFORCE_GT_7XX', 'GeForce GT 7xx'), ('GEFORCE_GTX_1050_TI', 'GeForce GTX 1050 Ti'), ('GEFORCE_GTX_1070_1080', 'GeForce GTX 1070/1080'), ('GEFORCE_GTX_1650_TI_MAX_Q', 'GeForce GTX 1650 ti Max-Q'), ('GEFORCE_GTX_1660_TI_MAX_Q', 'GeForce GTX 1660 ti Max-Q'), ('GEFORCE_GTX_7XX', 'GeForce GTX 7xx'), ('GEFORCE_MX_SERIES', 'GeForce MX Series'), ('GEFORCE_RTX_2050', 'GeForce RTX 2050'), ('GEFORCE_RTX_2070', 'GeForce RTX 2070'), ('GEFORCE_RTX_2070_MAX_Q', 'GeForce RTX 2070 Max-Q'), ('GEFORCE_RTX_2070_SUPER', 'GeForce RTX 2070 Super'), ('GEFORCE_RTX_2070_SUPER_MAX_Q', 'GeForce RTX 2070 Super Max-Q'), ('GEFORCE_RTX_2080', 'GeForce RTX 2080'), ('GEFORCE_RTX_2080_SUPER', 'GeForce RTX 2080 Super'), ('GEFORCE_RTX_2080_SUPER_MAX_Q', 'GeForce RTX 2080 Super Max-Q'), ('GEFORCE_RTX_3060_MAX_Q', 'GeForce RTX 3060 Max-Q'), ('GEFORCE_RTX_3070_MAX_Q', 'GeForce RTX 3070 Max-Q'), ('IRIS_XE_MAX', 'Iris Xe Max'), ('QUADRO', 'Quadro'), ('RTX_A_SERIES', 'RTX A Series'), ('RADEON', 'Radeon')], max_length=38, verbose_name='Відеокарта')),
                ('videocard_memory', models.IntegerField(verbose_name='Відео память')),
                ('HDD_aviable', models.BooleanField(verbose_name='HDD диск')),
                ('HDD_size', models.IntegerField(blank=True, null=True, verbose_name='Розмір HDD диску')),
                ('SSD_aviable', models.BooleanField(verbose_name='SSD диск')),
                ('SSD_size', models.IntegerField(blank=True, null=True, verbose_name='Розмір SSD диску')),
                ('RAM_size', models.IntegerField(verbose_name='Кількість оперативної памяті')),
                ('Ram_type', models.CharField(choices=[('DDR4', 'DDR4'), ('DDR3', 'DDR3'), ('DDR2', 'DDR2')], max_length=4, verbose_name='Тип оперативної памяті')),
                ('RAM_slots', models.IntegerField(verbose_name='Кількість розємів для оперативної памяті')),
                ('processor_series', models.CharField(choices=[('Intel_Core_i3', 'Intel Core i3'), ('Intel_Core_i5', 'Intel Core i5'), ('Intel_Core_i7', 'Intel Core i7'), ('Intel_Core_i9', 'Intel Core i9'), ('Intel_Pentium', 'Intel Pentium'), ('Intel_Atom', 'Intel Atom'), ('Intel Celeron', 'Intel Celeron'), ('Intel_Core_M', 'Intel Core M'), ('Intel_Xeon', 'Intel Xeon'), ('Amd_Ryzen_3', 'Amd Ryzen 3'), ('Amd_Ryzen_5', 'Amd Ryzen 5'), ('Amd_Ryzen_7', 'Amd Ryzen 7'), ('Amd_Ryzen_9', 'Amd Ryzen 9'), ('AMD_A_E_FX_SERIES', 'Amd A/E/FX Series'), ('AMD_ATHLON', 'Amd Athlon'), ('Apple_M', 'Apple M')], max_length=17, verbose_name='Процессор')),
                ('processor_hertz', models.CharField(max_length=20, verbose_name='Частота просессора')),
                ('processor_generation', models.IntegerField(verbose_name='Покоління процессора')),
                ('cores_num', models.IntegerField(verbose_name='Кількість ядер')),
                ('OS', models.CharField(choices=[('WIN7', 'Віндовс 7'), ('WIN8', 'Віндовс 8'), ('WIN10PRO', 'Віндовс 10 Pro'), ('WIN10HOME', 'Віндовс 10 Home'), ('MAC', 'Мак ОС'), ('LIN', 'Лінукс'), ('WITHOUTOS', 'Без операційної системи')], max_length=9, verbose_name='Операційна система')),
                ('wifi_adapter', models.BooleanField(verbose_name='Wifi адаптер')),
                ('bluetooth_adpter', models.BooleanField(verbose_name='Bluetooth адаптер')),
                ('web_camera', models.BooleanField(verbose_name='Веб камера')),
                ('optical_drive', models.BooleanField(verbose_name='Оптичний привід')),
                ('fingerprint_scaner', models.BooleanField(verbose_name='Сканер відбитку пальця')),
                ('connectors_ports', models.CharField(max_length=100, verbose_name='Розєми та порти')),
                ('colour', models.CharField(choices=[('WHITE', 'Білий'), ('BLACK', 'Чорний'), ('RED', 'Червоний'), ('BLUE', 'Синій'), ('PINK', 'Рожевий'), ('SILVER', 'Сріблястий'), ('VIOLET', 'Фіолетовий'), ('GRAY', 'Сірий'), ('GOLD', 'Золотий'), ('BROWN', 'Коричневий'), ('GREEN', 'Зелений'), ('ORANGE', 'Оранжений'), ('PAINTING', 'Малюнок')], max_length=8, verbose_name='Колір')),
                ('acumulator_size', models.IntegerField(verbose_name='Обєм акумулятора')),
                ('width', models.FloatField(verbose_name='Ширина')),
                ('height', models.FloatField(verbose_name='Висота')),
                ('lenght', models.FloatField(verbose_name='Довжина')),
                ('weight', models.FloatField(verbose_name='Вага')),
                ('producing_country', models.CharField(choices=[('USA', 'Сполучені Штати'), ('JPN', 'Японія'), ('KOR', 'Південна Корея'), ('DE', 'Німеччина'), ('SG', 'Сінгапур'), ('UK', 'Великобританія'), ('SE', 'Швеція'), ('IE', 'Ірландія'), ('IL', 'Ізраїль'), ('CA', 'Канада'), ('CH', 'Швейцарія'), ('FI', 'Фінляндія'), ('FR', 'Франція'), ('NL', 'Нідерланди'), ('NO', 'Норвегія'), ('CZ', 'Чехія'), ('DK', 'Данія'), ('IN', 'Індія'), ('ID', 'Індонезія'), ('AE', 'Арабські Імірати'), ('ASTL', 'Австралія'), ('AUST', 'Австрія'), ('IT', 'Італія'), ('ES', 'Іспанія'), ('PK', 'Пакістан'), ('RUS', 'росія')], max_length=4, verbose_name='Країна виробник')),
            ],
            options={
                'verbose_name': 'Ноутбук',
                'verbose_name_plural': 'Ноутбуки',
            },
        ),
    ]
