# Generated by Django 4.1.4 on 2023-02-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('laptop', 'Ноутбук'), ('PC', 'Компютер'), ('Phone', 'Телефон'), ('Tablet', 'Планшет'), ('TV', 'Телевізор'), ('Monitor', 'Монітор'), ('Headphones', 'Навушники'), ('Mouse', 'Мишка'), ('Keyboard', 'Клавіатура'), ('Flash Drive', 'Флешка'), ('Watch', 'Годинник'), ('Processor', 'Процессор'), ('Videocard', 'Відеокарта'), ('RAM', 'Оперативна память'), ('Disk', 'Диск'), ('Motherboard', 'Материнська плата'), ('Kuller', 'Система охолодження'), ('Power Block', 'Блок живлення'), ('Case', 'Корпус')], max_length=25, primary_key=True, serialize=False, verbose_name='Назва'),
        ),
    ]
